# kk explain deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-example
spec:
  selector:
    matchLabels: # 必须和下面pods的labels一致
      app: example
  replicas: 3
  strategy:
    # Recreate 不常用，因为选它会在更新pod时，先结束所有正常pod后，再启动新的，服务会出现一段时间停机
    type: Recreate # or RollingUpdate
    rollingUpdate: # rollingUpdate的进一步设置
      maxSurge: 2
      maxUnavailable: 1
  progressDeadlineSeconds: 10 # 控制器处于 running状态的最长时间，超时后控制器会变为 失败状态
  minReadySeconds: 10 # 新的pods变为ready状态的最短时间
  revisionHistoryLimit: 2 # 保留的pod历史版本数，默认是10
  paused: false # 默认false，用于暂停和恢复部署，当true时，pod模板中的spec修改不会触发任何新的部署
  template:
    metadata:
      name: pods-simple-pod
      labels:
        app: example
    spec:
      containers:
        - name: pods-simple-container
          command:
            - sleep
            - "3600"
          image: busybox
