apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-example
spec:
  selector:
    matchLabels: # 必须和下面pods的labels一致
      app: example
  replicas: 3
  template:
    metadata:
      name: pods-simple-pod
      labels:
        app: example
    spec:
      containers:
        - name: pods-simple-container
          command:
            - sleep
            - "3600"
          image: busybox
