# https://golangci-lint.run/usage/configuration/
run:
  timeout: 2m
  tests: false
  go: "1.18"

# golangci-lint config path
# golangci-lint linters 查看打开的linters
linters:
  disable-all: true
  enable:
    - typecheck
    - staticcheck
    - govet
    - gocritic
issues:
  exclude-dirs: # 支持regex
    - gateway
  exclude-dirs-use-default: true
  exclude-files: # example,  / 会被纠正
    - ".*\\.my\\.go$"
    - lib/bad.go
    - vendor/*
  exclude-generated-strict: true  # 排除生成的代码
  new-from-rev: HEAD # 只显示指定的 Git 提交版本之后创建的问题
  fix: false # 让linter自动修复问题（若linter支持）

# golangci-lint help linters
#linters-settings:
#  govet:
#    check-shadowing: true
#    disable-all: true
#    enable:
#      - asmdecl
#      - assign
#      - atomic
#      - atomicalign
#      - bools
#      - buildtag
#      - cgocall
#      - composites
#      - copylocks
#      - httpresponse
#      - loopclosure
#      - lostcancel
#      - nilfunc
#      - nilness
#      - printf
#      - shadow
#      - shift
#      - stdmethods
#      - structtag
#      - tests
#      - unmarshal
#      - unreachable
#      - unsafeptr
#      - unusedresult
#
#  staticcheck:
#    go: "1.18"
#    checks: [ "all", "-SA3*", "-SA6000", "-SA6001", "-SA6003", "-ST*", "ST1006", "ST1008", "ST1016", "-QF1" ]
#
#  gocritic:
#    enabled-tags:
#      - diagnostic
#      - experimental
#      - opinionated
#      - style
#    enabled-checks:
#      - sliceClear
#    disabled-tags:
#      - performance
#    disabled-checks:
#      - assignOp
#      - badLock
#      - badRegexp
#      - codegenComment
#      - commentFormatting
#      - commentedOutCode
#      - docStub
#      - dupArg
#      - dupBranchBody
#      - dupCase
#      - dupImport
#      - exitAfterDefer
#      - externalErrorReassign
#      - flagDeref
#      - hexLiteral
#      - ifElseChain
#      - importShadow
#      - initClause
#      - mapKey
#      - nestingReduce
#      - newDeref
#      - redundantSprint
#      - regexpMust
#      - regexpPattern
#      - regexpSimplify
#      - ruleguard
#      - sloppyLen
#      - sloppyTypeAssert
#      - sortSlice
#      - sprintfQuotedString
#      - sqlQuery
#      - stringConcatSimplify
#      - syncMapLoadAndDelete
#      - tooManyResultsChecker
#      - typeDefFirst
#      - typeUnparen
#      - underef
#      - unlabelStmt
#      - unlambda
#      - unnecessaryBlock
#      - unnecessaryDefer
#      - yodaStyleExpr
#      - whyNoLint
#      - paramTypeCombine
#      - emptyStringTest