---
apiVersion: v1
kind: Pod
metadata:
  name: privileged-simple-pod
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: busybox
      name: privileged-simple-pod
      securityContext:
        privileged: true
        runAsNonRoot: false
        runAsUser: 1000 # uid
        runAsGroup: 1000 # gid
        procMount: "Unmasked" # 可以设置为 "Default"、"Unmasked" 或 "Masked"
        readOnlyRootFilesystem: true