apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3 # 副本数量
  selector:
    matchLabels:
      app1: hellok8s
      app: aaa
  template:
    metadata:
      labels:
        app1: hellok8s
        app: aaa
    spec:
      containers:
        - image: leigg/hellok8s:v2
          name: hellok8s-container